sudo: required
services:
  - docker

before_install:
  - docker build -t swanand7731/docker-react -f Dockerfile.dev .

  script:
    - docker run swanand7731/docker-react npm run test -- --coverage


